"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"
import { useRouter, usePathname } from "next/navigation"

export type Language = "en" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({
  children,
  initialLanguage = "en",
}: {
  children: React.ReactNode
  initialLanguage?: Language
}) {
  const [language, setLanguageState] = useState<Language>(initialLanguage)
  const router = useRouter()
  const pathname = usePathname()

  // Sync state if initialLanguage changes (e.g. navigation)
  useEffect(() => {
    setLanguageState(initialLanguage)
  }, [initialLanguage])

  useEffect(() => {
    const saved = localStorage.getItem("preferred_lang") as Language
    // We only use saved pref if we are NOT on a specific lang route?
    // Actually, the URL is the truth. We just update localStorage for future sessions.
    if (initialLanguage) {
      localStorage.setItem("preferred_lang", initialLanguage)
      document.documentElement.lang = initialLanguage
    }
  }, [initialLanguage])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("preferred_lang", lang)
    document.documentElement.lang = lang

    // Update URL
    // Assumption: Path is /[lang]/[audience]/...
    const segments = pathname.split("/").filter(Boolean)
    if (segments.length >= 2) {
      segments[0] = lang
      const newPath = `/${segments.join("/")}`
      router.push(newPath)
    }
  }

  const t = (key: string) => {
    return uiTranslations[language]?.[key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

const uiTranslations: Record<Language, Record<string, string>> = {
  en: {
    "nav.affiliate": "Affiliate",
    "nav.webmaster": "Webmaster",
    "nav.networks": "Networks",
    "nav.rankings": "Rankings",
    "nav.formats": "Formats",
    "nav.blog": "Blog",
    "nav.news": "News",
    "nav.guides": "Guides",
    "nav.tools": "Tools",
    "nav.advertise": "Advertise",
    "nav.knowledgeBase": "Knowledge Base",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.methodology": "Methodology",
    "nav.terms": "Terms",
    "nav.privacy": "Privacy",
    "nav.disclaimer": "Disclaimer",
    "nav.caseStudies": "Case Studies",
    "nav.jobs": "Jobs",
    "nav.events": "Events",
    "home.industryUpdates": "Recent Articles",
    "home.topNetworks": "Top Networks by Format",
    "home.trendingGuides": "Trending Guides",
    "home.caseStudies": "Case Studies",
    "common.viewAll": "View all",
    "common.viewRankings": "View rankings",
    "common.search": "Search...",
    "common.more": "View more",
    "common.subscribe": "Subscribe",
    "common.newsletter": "Newsletter",
    "common.emailAddress": "Email address",
    "common.newsletterDesc": "Get the latest ad tech news delivered to your inbox.",
    "common.downloadPDF": "Download PDF",
    "common.downloadBreakdown": "Download Breakdown",
    "common.downloadDesc": "Get the full PDF breakdown including exact placement screenshots.",
    "common.viewDetail": "View Details",
    "common.allNetworks": "All Networks",
    "common.allRankings": "All Rankings",
    "common.allFormats": "All Formats",
    "common.allGuides": "All Guides",
    "common.allTools": "All Tools",
    "common.allFormatsFilter": "Formats",
    "common.allPaymentTerms": "All Payment Terms",
    "common.sortByName": "Sort by Name",
    "common.sortByMinPayout": "Sort by Min Payout",
    "common.directory": "Directory",
    "common.resources": "Resources",
    "events.title": "Industry Events",
    "events.subtitle": "Discover the most important affiliate marketing and ad tech conferences worldwide.",
    "events.noEvents": "No events found.",
    "common.company": "Company",
    "common.legal": "Legal",
    "network.payout": "Min Payout",
    "network.frequency": "Frequency",
    "network.rating": "Rating",
    "network.methods": "Methods",
    "network.geos": "GEOs",
    "network.visit": "Visit Site",
    "network.similar": "Similar Networks",
    "network.compareNetworks": "Compare {count} ad networks for publishers",
    "network.signupPublisher": "Sign up as a publisher",
    "network.goToSite": "Go to Site",
    "network.editorialNote": "Review",
    "network.pros": "Pros",
    "network.cons": "Cons",
    "network.ratingsFormat": "Ratings by Format",
    "network.stability": "Stability",
    "network.support": "Support",
    "article.related": "Related Articles",
    "article.detailedCaseAnalysis": "Detailed Case Analysis",
    "article.setupStrategy": "Setup & Strategy",
    "article.trafficDistribution": "Traffic Distribution",
    "article.adPlacements": "Ad Placements",
    "article.finalResults": "Final Results",
    "article.keyLessons": "Key Lessons",
    "footer.forEducational": "For educational purposes only.",
    "blog.allPosts": "All",
    "blog.news": "News",
    "blog.reviews": "Reviews",
    "blog.caseStudies": "Case Studies",
    "blog.guides": "Guides",
    "blog.trends": "Trends",
    "rankings.title": "Network Rankings",
    "rankings.description": "Our rankings are based on performance data, publisher feedback, and editorial review.",
    "rankings.bestNetworks": "Best {format} Networks",
    "rankings.networksRanked": "{count} networks ranked",
    "tools.rpmCalculator": "RPM Calculator",
    "tools.formatPicker": "Ad Format Picker",
    "tools.formatDemo": "Format Demo",
    "jobs.backToJobs": "Back to Jobs",
    "jobs.title": "Jobs",
    "jobs.subtitle": "Find the best opportunities in affiliate marketing and ad tech.",
    "jobs.searchPlaceholder": "Search jobs...",
    "jobs.noJobs": "No jobs found matching your criteria.",
    "jobs.location": "Location",
    "jobs.experience": "Experience",
    "jobs.aboutCompany": "About the Company",
    "jobs.responsibilities": "Responsibilities",
    "jobs.requirements": "Requirements",
    "jobs.apply": "Apply Now",
    "jobs.loc.remote": "Remote",
    "jobs.loc.office": "Office",
    "jobs.loc.hybrid": "Hybrid",
    "jobs.exp.no_experience": "No experience",
    "jobs.exp.1_year": "1 year",
    "jobs.exp.2_years": "2 years",
    "jobs.exp.3_years": "3 years",
    "jobs.exp.3_plus_years": "3+ years",
    "events.region": "Region",
    "events.date": "Date",
    "events.allRegions": "All Regions",
    "events.allCategories": "All Categories",
    "events.selectMonth": "Select Month",
    "events.reg.cis": "CIS",
    "events.reg.europe": "Europe",
    "events.reg.us": "US",
    "events.reg.middle_east": "Middle East",
    "events.reg.latin_america": "Latin America",
    "events.reg.asia": "Asia",
    "events.reg.online": "Online",
    "jobs.pos.hr": "HR",
    "jobs.pos.smm": "SMM",
    "jobs.pos.copywriter": "Copywriter",
    "jobs.pos.seo": "SEO Specialist",
    "jobs.pos.designer": "Designer",
    "jobs.pos.marketing": "Marketing",
    "jobs.pos.pr": "PR",
    "jobs.pos.affiliate_manager": "Affiliate Manager",
    "jobs.pos.sales_manager": "Sales Manager",
    "jobs.pos.project_manager": "Project Manager",
    "jobs.pos.account_manager": "Account Manager",
    "jobs.pos.farmer": "Farmer",
    "jobs.pos.tech_specialist": "Technical Specialist",
    "jobs.pos.media_buyer": "Media Buyer",
    "jobs.pos.bizdev": "Business Developer",
    "jobs.lvl.junior": "Junior",
    "jobs.lvl.middle": "Middle",
    "jobs.lvl.senior": "Senior",
    "jobs.lvl.team_lead": "Team-Lead",
    "jobs.lvl.c_level": "+ C-Level",
    "jobs.sal.after_interview": "After Interview",
    "jobs.sal.500-1000": "500-1000$",
    "jobs.sal.1000-2500": "1000-2500$",
    "jobs.sal.3500-4500": "3500-4500$",
    "jobs.sal.4500-5000": "4500-5000$",
    "jobs.sal.5000_plus": "5000$+",
    "jobs.applyFilters": "Apply Filters",
    "jobs.resetFilters": "Reset Filters",
    "jobs.allLocations": "All Locations",
    "jobs.allPositions": "All Positions",
    "jobs.allLevels": "All Levels",
    "jobs.allExperiences": "All Experiences",
    "knowledge.title": "Knowledge Base",
    "knowledge.description": "Essential terms and concepts in affiliate marketing and ad tech.",
    "knowledge.traffic": "Traffic Sources",
    "knowledge.monetizationModels": "Monetization Models",
    "knowledge.adFormats": "Ad Formats",
    "knowledge.metrics": "Metrics and KPI",
    "knowledge.adNetworks": "Ad Networks",
    "knowledge.technical": "Technical Terms",
    "knowledge.webmaster": "Webmaster Tools",
    "knowledge.financial": "Financial Terms",
    "common.articles": "Articles",
    "common.viewAllResults": "View all {count} results",
    "common.socials": "Socials",
  },
  ru: {
    "nav.affiliate": "Арбитражник",
    "nav.webmaster": "Вебмастер",
    "nav.networks": "Сети",
    "nav.rankings": "Рейтинги",
    "nav.formats": "Форматы",
    "nav.blog": "Блог",
    "nav.news": "Новости",
    "nav.guides": "Гайды",
    "nav.tools": "Инструменты",
    "nav.advertise": "Реклама",
    "nav.knowledgeBase": "База Знаний",
    "nav.home": "Главная",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.methodology": "Методология",
    "nav.terms": "Условия",
    "nav.privacy": "Конфиденциальность",
    "nav.disclaimer": "Отказ от ответственности",
    "nav.caseStudies": "Кейсы",
    "nav.jobs": "Вакансии",
    "nav.events": "Ивенты",
    "home.industryUpdates": "Свежие Статьи",
    "home.topNetworks": "Лучшие сети по форматам",
    "home.trendingGuides": "Популярные гайды",
    "home.caseStudies": "Кейсы",
    "common.viewAll": "Смотреть все",
    "common.viewRankings": "Смотреть рейтинги",
    "common.search": "Поиск...",
    "common.more": "Подробнее",
    "common.subscribe": "Подписаться",
    "common.newsletter": "Рассылка",
    "common.emailAddress": "Email адрес",
    "common.newsletterDesc": "Получайте последние новости рекламных технологий на вашу почту.",
    "common.downloadPDF": "Скачать PDF",
    "common.downloadBreakdown": "Скачать отчет",
    "common.downloadDesc": "Получите полный PDF-отчет со скриншотами размещений.",
    "common.viewDetail": "Подробнее",
    "common.allNetworks": "Все сети",
    "common.allRankings": "Все рейтинги",
    "common.allFormats": "Все форматы",
    "common.allGuides": "Все гайды",
    "common.allTools": "Все инструменты",
    "common.allFormatsFilter": "Форматы",
    "common.allPaymentTerms": "Все условия оплаты",
    "common.sortByName": "Сортировать по названию",
    "common.sortByMinPayout": "Сортировать по мин. выплате",
    "common.directory": "Каталог",
    "common.resources": "Ресурсы",
    "events.title": "Отраслевые Ивенты",
    "events.subtitle": "Откройте для себя самые важные конференции по арбитражу трафика и ad tech во всем мире.",
    "events.noEvents": "Ивентов не найдено.",
    "common.company": "Компания",
    "common.legal": "Правовая информация",
    "network.payout": "Мин. выплата",
    "network.frequency": "Частота",
    "network.rating": "Рейтинг",
    "network.methods": "Методы",
    "network.geos": "Гео",
    "network.visit": "Перейти на сайт",
    "network.similar": "Похожие сети",
    "network.compareNetworks": "Сравните {count} рекламных сетей для вебмастеров",
    "network.signupPublisher": "Зарегистрироваться как паблишер",
    "network.goToSite": "Перейти на сайт",
    "network.editorialNote": "Обзор",
    "network.pros": "Плюсы",
    "network.cons": "Минусы",
    "network.ratingsFormat": "Рейтинги по форматам",
    "network.stability": "Стабильность",
    "network.support": "Саппорт",
    "article.related": "Похожие статьи",
    "article.detailedCaseAnalysis": "Детальный анализ кейса",
    "article.setupStrategy": "Настройка и стратегия",
    "article.trafficDistribution": "Распределение трафика",
    "article.adPlacements": "Размещение рекламы",
    "article.finalResults": "Финальные результаты",
    "article.keyLessons": "Ключевые выводы",
    "footer.forEducational": "Только в образовательных целях.",
    "blog.allPosts": "Все",
    "blog.news": "Новости",
    "blog.reviews": "Обзоры",
    "blog.caseStudies": "Кейсы",
    "blog.guides": "Гайды",
    "blog.trends": "Тренды",
    "rankings.title": "Рейтинги сетей",
    "rankings.description":
      "Наши рейтинги основаны на данных о производительности, отзывах вебмастеров и редакционном обзоре.",
    "rankings.bestNetworks": "Лучшие {format} сети",
    "rankings.networksRanked": "{count} сетей в рейтинге",
    "tools.rpmCalculator": "Калькулятор RPM",
    "tools.formatPicker": "Подбор формата рекламы",
    "tools.checklist": "Чеклист пре-монетизации",
    "tools.formatDemo": "Демо Форматов",
    "jobs.backToJobs": "Назад к вакансиям",
    "jobs.title": "Вакансии",
    "jobs.subtitle": "Лучшие предложения в арбитраже и ad tech.",
    "jobs.searchPlaceholder": "Поиск вакансий...",
    "jobs.noJobs": "Вакансий по вашему запросу не найдено.",
    "jobs.location": "Местоположение",
    "jobs.experience": "Опыт работы",
    "jobs.aboutCompany": "О компании",
    "jobs.responsibilities": "Обязанности",
    "jobs.requirements": "Требования",
    "jobs.apply": "Откликнуться",
    "jobs.loc.remote": "Удаленно",
    "jobs.loc.office": "Офис",
    "jobs.loc.hybrid": "Гибрид",
    "jobs.exp.no_experience": "Без опыта",
    "jobs.exp.1_year": "1 год",
    "jobs.exp.2_years": "2 года",
    "jobs.exp.3_years": "3 года",
    "jobs.exp.3_plus_years": "3+ года",
    "events.region": "Регион",
    "events.date": "Дата",
    "events.allRegions": "Все регионы",
    "events.allCategories": "Все категории",
    "events.selectMonth": "Выбрать месяц",
    "events.reg.cis": "СНГ",
    "events.reg.europe": "Европа",
    "events.reg.us": "США",
    "events.reg.middle_east": "Ближний Восток",
    "events.reg.latin_america": "Латинская Америка",
    "events.reg.asia": "Азия",
    "events.reg.online": "Онлайн",
    "jobs.pos.hr": "HR",
    "jobs.pos.smm": "SMM",
    "jobs.pos.copywriter": "Копирайтер",
    "jobs.pos.seo": "SEO Специалист",
    "jobs.pos.designer": "Дизайнер",
    "jobs.pos.marketing": "Маркетолог",
    "jobs.pos.pr": "PR",
    "jobs.pos.affiliate_manager": "Affiliate Менеджер",
    "jobs.pos.sales_manager": "Sales Менеджер",
    "jobs.pos.project_manager": "Project Менеджер",
    "jobs.pos.account_manager": "Account Менеджер",
    "jobs.pos.farmer": "Фармер",
    "jobs.pos.tech_specialist": "Технический Специалист",
    "jobs.pos.media_buyer": "Медиабайер",
    "jobs.pos.bizdev": "Бизнес-девелопер",
    "jobs.lvl.junior": "Джуниор",
    "jobs.lvl.middle": "Мидл",
    "jobs.lvl.senior": "Синьор",
    "jobs.lvl.team_lead": "Team-Lead",
    "jobs.lvl.c_level": "+ C-Level",
    "jobs.sal.after_interview": "После собеседования",
    "jobs.sal.500-1000": "500-1000$",
    "jobs.sal.1000-2500": "1000-2500$",
    "jobs.sal.3500-4500": "3500-4500$",
    "jobs.sal.4500-5000": "4500-5000$",
    "jobs.sal.5000_plus": "5000$+",
    "jobs.applyFilters": "Применить фильтры",
    "jobs.resetFilters": "Сбросить фильтры",
    "jobs.allLocations": "Все локации",
    "jobs.allPositions": "Все позиции",
    "jobs.allLevels": "Все уровни",
    "jobs.allExperiences": "Любой опыт",
    "knowledge.title": "База Знаний",
    "knowledge.description": "Основные термины и понятия в арбитраже трафика и рекламных технологиях.",
    "knowledge.traffic": "Источники Трафика",
    "knowledge.monetizationModels": "Модели Монетизации",
    "knowledge.adFormats": "Рекламные Форматы",
    "knowledge.metrics": "Метрики и KPI",
    "knowledge.adNetworks": "Рекламные Сети",
    "knowledge.technical": "Технические Термины",
    "knowledge.webmaster": "Инструменты Вебмастера",
    "knowledge.financial": "Финансовые Термины",
    "common.articles": "Статьи",
    "common.viewAllResults": "Посмотреть все результаты",
    "common.socials": "Социальные сети",
  },
}
